apiVersion: v1
kind: Service
metadata:
  name: hotel404-backend
  namespace: hotel404
spec:
  selector:
    app: hotel404-backend
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
  type: ClusterIP
