apiVersion: v1
kind: Service
metadata:
  name: hotel404-backend-service
spec:
  type: ClusterIP
  selector:
    app: hotel404-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
