apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-backend
  namespace: hotel404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel404-backend
  template:
    metadata:
      labels:
        app: hotel404-backend
    spec:
      containers:
      - name: hotel404-backend
        image: deividasmalaska/hotel404-backend:latest
        ports:
        - containerPort: 7700
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      imagePullSecrets:
        - name: dockerhub-secret