apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel404-frontend
  template:
    metadata:
      labels:
        app: hotel404-frontend
    spec:
      containers:
      - name: hotel404-frontend
        image: DEIVIDOCKER_USERNAME/hotel404-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"   # Minimum 0.25 CPU (250 millicores)
            memory: "256Mi"  # Minimum 512MB RAM
          limits:
            cpu: "250m"   # Maximum 0.5 CPU
            memory: "512Mi"  # Maximum 1GB RAM