apiVersion: v1
kind: Service
metadata:
  name: hotel404-frontend
  namespace: hotel404
spec:
  selector:
    app: hotel404-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
