apiVersion: v1
kind: Service
metadata:
  name: hotel404-microservice
  namespace: hotel404
spec:
  selector:
    app: hotel404-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
