apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-microservice
  namespace: hotel404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel404-microservice
  template:
    metadata:
      labels:
        app: hotel404-microservice
    spec:
      containers:
      - name: hotel404-microservice
        image: deividasmalaska/hotel404-microservice:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      imagePullSecrets:
        - name: dockerhub-secret
