apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel404-backend
  template:
    metadata:
      labels:
        app: hotel404-backend
    spec:
      containers:
      - name: hotel404-backend
        image: hotel404containerregistry.azurecr.io/hotel404-backend:latest  # Use the correct image here
        imagePullPolicy: Always
        ports:
          - containerPort: 8080   # NGINX listens on port 80 (per your Dockerfile)
        resources:
          requests:
            cpu: 126m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hotel404-backend
spec:
  loadBalancerIP: 9.223.137.106
  selector:
    app: hotel404-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080      # External port to reach the service
      targetPort: 8080    # Matches containerPort (NGINX)
