apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel404-frontend
  template:
    metadata:
      labels:
        app: hotel404-frontend
    spec:
      containers:
      - name: hotel404-frontend
        image: deividasmalaska/hotel404-frontend:latest  # Use the correct image here
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80   # NGINX listens on port 80 (per your Dockerfile)
        resources:
          requests:
            cpu: 126m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hotel404-frontend
spec:
  selector:
    app: hotel404-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80      # External port to reach the service
      targetPort: 80    # Matches containerPort (NGINX)
