name: Run Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies in the backend directory
      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./hotel404/backend

      # Install dependencies in the frontend directory
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./hotel404/frontend

      # Run Jest tests in the backend directory
      - name: Run Backend Jest tests
        run: npm test
        working-directory: ./hotel404/backend

      # Run Jest tests in the frontend directory
      - name: Run Frontend Jest tests
        run: npm test
        working-directory: ./hotel404/frontend