name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DEIVIDOCKER_PASSWORD }}" | docker login -u ${{ secrets.DEIVIDOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DEIVIDOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }} -f hotel404/backend/Dockerfile hotel404/backend/
          docker push ${{ secrets.DEIVIDOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}
          docker build -t ${{ secrets.DEIVIDOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }} -f hotel404/frontend/Dockerfile hotel404/frontend/
          docker push ${{ secrets.DEIVIDOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}

      - name: Set up Kubernetes
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy to AKS
        run: |
          kubectl apply -f .github/workflows/deployment.yaml
          kubectl set image deployment/hotel404-microservice hotel404-microservice=${{ secrets.DEIVIDOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}
