name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }} -f hotel404/backend/Dockerfile hotel404/backend/
          docker push ${{ secrets.DOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }} -f hotel404/frontend/Dockerfile hotel404/frontend/
          docker push ${{ secrets.DOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3

      - name: Login to Azure using Managed Identity
        run: az login --identity

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/hotel404-microservice hotel404-microservice=${{ secrets.DOCKER_USERNAME }}/hotel404-microservice:${{ github.sha }}
