name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login hotel404ContainerRegistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t hotel404ContainerRegistry.azurecr.io/my-microservice:latest .
          docker push hotel404ContainerRegistry.azurecr.io/my-microservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Authenticate with AKS
        run: az aks get-credentials --resource-group hotel404ResourceGroup --name hotel404AKSCluster --overwrite-existing

      - name: Deploy to AKS
        run: kubectl apply -f k8s/deployment.yaml
