# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel404-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel404-backend
  template:
    metadata:
      labels:
        app: hotel404-backend
    spec:
      containers:
      - name: hotel404-backend
        image: $REGISTRY_USERNAME/hotel404-backend:$IMAGE_TAG
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
        # Add these if you have health checks
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 8080
      imagePullSecrets:
      - name: dockerhub-creds  # If using private Docker Hub repo